# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graphManagerWidgetUi.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(403, 546)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.Options = QtWidgets.QWidget()
        self.Options.setObjectName("Options")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Options)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.GB_numberFormat = QtWidgets.QGroupBox(self.Options)
        self.GB_numberFormat.setObjectName("GB_numberFormat")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.GB_numberFormat)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.LA_xNumberFormat = QtWidgets.QLabel(self.GB_numberFormat)
        self.LA_xNumberFormat.setObjectName("LA_xNumberFormat")
        self.gridLayout_4.addWidget(self.LA_xNumberFormat, 1, 0, 1, 1)
        self.LA_yNumberFormat = QtWidgets.QLabel(self.GB_numberFormat)
        self.LA_yNumberFormat.setObjectName("LA_yNumberFormat")
        self.gridLayout_4.addWidget(self.LA_yNumberFormat, 2, 0, 1, 1)
        self.LA_numberOfDigits = QtWidgets.QLabel(self.GB_numberFormat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LA_numberOfDigits.sizePolicy().hasHeightForWidth())
        self.LA_numberOfDigits.setSizePolicy(sizePolicy)
        self.LA_numberOfDigits.setObjectName("LA_numberOfDigits")
        self.gridLayout_4.addWidget(self.LA_numberOfDigits, 0, 2, 1, 1)
        self.CoB_xNumberFormat = QtWidgets.QComboBox(self.GB_numberFormat)
        self.CoB_xNumberFormat.setObjectName("CoB_xNumberFormat")
        self.CoB_xNumberFormat.addItem("")
        self.CoB_xNumberFormat.addItem("")
        self.CoB_xNumberFormat.addItem("")
        self.gridLayout_4.addWidget(self.CoB_xNumberFormat, 1, 1, 1, 1)
        self.LE_xAmountOfDigits = QtWidgets.QLineEdit(self.GB_numberFormat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_xAmountOfDigits.sizePolicy().hasHeightForWidth())
        self.LE_xAmountOfDigits.setSizePolicy(sizePolicy)
        self.LE_xAmountOfDigits.setObjectName("LE_xAmountOfDigits")
        self.gridLayout_4.addWidget(self.LE_xAmountOfDigits, 1, 2, 1, 1)
        self.CoB_yNumberFormat = QtWidgets.QComboBox(self.GB_numberFormat)
        self.CoB_yNumberFormat.setObjectName("CoB_yNumberFormat")
        self.CoB_yNumberFormat.addItem("")
        self.CoB_yNumberFormat.addItem("")
        self.CoB_yNumberFormat.addItem("")
        self.gridLayout_4.addWidget(self.CoB_yNumberFormat, 2, 1, 1, 1)
        self.LE_yAmountOfDigits = QtWidgets.QLineEdit(self.GB_numberFormat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_yAmountOfDigits.sizePolicy().hasHeightForWidth())
        self.LE_yAmountOfDigits.setSizePolicy(sizePolicy)
        self.LE_yAmountOfDigits.setObjectName("LE_yAmountOfDigits")
        self.gridLayout_4.addWidget(self.LE_yAmountOfDigits, 2, 2, 1, 1)
        self.LA_typeNumberFormat = QtWidgets.QLabel(self.GB_numberFormat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LA_typeNumberFormat.sizePolicy().hasHeightForWidth())
        self.LA_typeNumberFormat.setSizePolicy(sizePolicy)
        self.LA_typeNumberFormat.setObjectName("LA_typeNumberFormat")
        self.gridLayout_4.addWidget(self.LA_typeNumberFormat, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.GB_numberFormat, 1, 0, 1, 1)
        self.GB_grid = QtWidgets.QGroupBox(self.Options)
        self.GB_grid.setObjectName("GB_grid")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.GB_grid)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.ChB_enableXGrid = QtWidgets.QCheckBox(self.GB_grid)
        self.ChB_enableXGrid.setObjectName("ChB_enableXGrid")
        self.gridLayout_6.addWidget(self.ChB_enableXGrid, 0, 0, 1, 1)
        self.ChB_enableYGrid = QtWidgets.QCheckBox(self.GB_grid)
        self.ChB_enableYGrid.setObjectName("ChB_enableYGrid")
        self.gridLayout_6.addWidget(self.ChB_enableYGrid, 1, 0, 1, 1)
        self.LA_gridOpacity = QtWidgets.QLabel(self.GB_grid)
        self.LA_gridOpacity.setObjectName("LA_gridOpacity")
        self.gridLayout_6.addWidget(self.LA_gridOpacity, 2, 0, 1, 1)
        self.HZ_gridOpacity = QtWidgets.QSlider(self.GB_grid)
        self.HZ_gridOpacity.setOrientation(QtCore.Qt.Horizontal)
        self.HZ_gridOpacity.setObjectName("HZ_gridOpacity")
        self.gridLayout_6.addWidget(self.HZ_gridOpacity, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.GB_grid, 1, 1, 1, 1)
        self.GB_axisScaling = QtWidgets.QGroupBox(self.Options)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GB_axisScaling.sizePolicy().hasHeightForWidth())
        self.GB_axisScaling.setSizePolicy(sizePolicy)
        self.GB_axisScaling.setObjectName("GB_axisScaling")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.GB_axisScaling)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ChB_xAutoscaling = QtWidgets.QCheckBox(self.GB_axisScaling)
        self.ChB_xAutoscaling.setEnabled(True)
        self.ChB_xAutoscaling.setText("")
        self.ChB_xAutoscaling.setChecked(True)
        self.ChB_xAutoscaling.setObjectName("ChB_xAutoscaling")
        self.gridLayout_3.addWidget(self.ChB_xAutoscaling, 2, 1, 1, 1)
        self.LE_yMin = QtWidgets.QLineEdit(self.GB_axisScaling)
        self.LE_yMin.setEnabled(False)
        self.LE_yMin.setObjectName("LE_yMin")
        self.gridLayout_3.addWidget(self.LE_yMin, 4, 3, 1, 1)
        self.LE_yMax = QtWidgets.QLineEdit(self.GB_axisScaling)
        self.LE_yMax.setEnabled(False)
        self.LE_yMax.setObjectName("LE_yMax")
        self.gridLayout_3.addWidget(self.LE_yMax, 4, 4, 1, 1)
        self.ChB_yAutoscaling = QtWidgets.QCheckBox(self.GB_axisScaling)
        self.ChB_yAutoscaling.setText("")
        self.ChB_yAutoscaling.setChecked(True)
        self.ChB_yAutoscaling.setObjectName("ChB_yAutoscaling")
        self.gridLayout_3.addWidget(self.ChB_yAutoscaling, 4, 1, 1, 1)
        self.LA_xMax = QtWidgets.QLabel(self.GB_axisScaling)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LA_xMax.sizePolicy().hasHeightForWidth())
        self.LA_xMax.setSizePolicy(sizePolicy)
        self.LA_xMax.setObjectName("LA_xMax")
        self.gridLayout_3.addWidget(self.LA_xMax, 1, 4, 1, 1)
        self.LA_xMin = QtWidgets.QLabel(self.GB_axisScaling)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LA_xMin.sizePolicy().hasHeightForWidth())
        self.LA_xMin.setSizePolicy(sizePolicy)
        self.LA_xMin.setObjectName("LA_xMin")
        self.gridLayout_3.addWidget(self.LA_xMin, 1, 3, 1, 1)
        self.LA_xScaling = QtWidgets.QLabel(self.GB_axisScaling)
        self.LA_xScaling.setObjectName("LA_xScaling")
        self.gridLayout_3.addWidget(self.LA_xScaling, 2, 0, 1, 1)
        self.LE_xMax = QtWidgets.QLineEdit(self.GB_axisScaling)
        self.LE_xMax.setEnabled(False)
        self.LE_xMax.setObjectName("LE_xMax")
        self.gridLayout_3.addWidget(self.LE_xMax, 2, 4, 1, 1)
        self.LA_yScaling = QtWidgets.QLabel(self.GB_axisScaling)
        self.LA_yScaling.setObjectName("LA_yScaling")
        self.gridLayout_3.addWidget(self.LA_yScaling, 4, 0, 1, 1)
        self.LE_xMin = QtWidgets.QLineEdit(self.GB_axisScaling)
        self.LE_xMin.setEnabled(False)
        self.LE_xMin.setObjectName("LE_xMin")
        self.gridLayout_3.addWidget(self.LE_xMin, 2, 3, 1, 1)
        self.LA_autoscale = QtWidgets.QLabel(self.GB_axisScaling)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LA_autoscale.sizePolicy().hasHeightForWidth())
        self.LA_autoscale.setSizePolicy(sizePolicy)
        self.LA_autoscale.setObjectName("LA_autoscale")
        self.gridLayout_3.addWidget(self.LA_autoscale, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.GB_axisScaling, 0, 0, 1, 2)
        self.GB_axisFormat = QtWidgets.QGroupBox(self.Options)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GB_axisFormat.sizePolicy().hasHeightForWidth())
        self.GB_axisFormat.setSizePolicy(sizePolicy)
        self.GB_axisFormat.setObjectName("GB_axisFormat")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.GB_axisFormat)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.LE_xSecondTicks = QtWidgets.QLineEdit(self.GB_axisFormat)
        self.LE_xSecondTicks.setEnabled(False)
        self.LE_xSecondTicks.setObjectName("LE_xSecondTicks")
        self.gridLayout_5.addWidget(self.LE_xSecondTicks, 5, 2, 1, 1)
        self.LE_yPrimaryTicks = QtWidgets.QLineEdit(self.GB_axisFormat)
        self.LE_yPrimaryTicks.setEnabled(False)
        self.LE_yPrimaryTicks.setObjectName("LE_yPrimaryTicks")
        self.gridLayout_5.addWidget(self.LE_yPrimaryTicks, 6, 1, 1, 1)
        self.LE_xPrimaryTicks = QtWidgets.QLineEdit(self.GB_axisFormat)
        self.LE_xPrimaryTicks.setEnabled(False)
        self.LE_xPrimaryTicks.setObjectName("LE_xPrimaryTicks")
        self.gridLayout_5.addWidget(self.LE_xPrimaryTicks, 5, 1, 1, 1)
        self.LA_xAxisFormat = QtWidgets.QLabel(self.GB_axisFormat)
        self.LA_xAxisFormat.setObjectName("LA_xAxisFormat")
        self.gridLayout_5.addWidget(self.LA_xAxisFormat, 5, 0, 1, 1)
        self.LE_ySecondTicks = QtWidgets.QLineEdit(self.GB_axisFormat)
        self.LE_ySecondTicks.setEnabled(False)
        self.LE_ySecondTicks.setObjectName("LE_ySecondTicks")
        self.gridLayout_5.addWidget(self.LE_ySecondTicks, 6, 2, 1, 1)
        self.LA_primaryTicksInterval = QtWidgets.QLabel(self.GB_axisFormat)
        self.LA_primaryTicksInterval.setObjectName("LA_primaryTicksInterval")
        self.gridLayout_5.addWidget(self.LA_primaryTicksInterval, 4, 1, 1, 1)
        self.LA_xAxisName = QtWidgets.QLabel(self.GB_axisFormat)
        self.LA_xAxisName.setObjectName("LA_xAxisName")
        self.gridLayout_5.addWidget(self.LA_xAxisName, 1, 1, 1, 1)
        self.LA_yAxisName = QtWidgets.QLabel(self.GB_axisFormat)
        self.LA_yAxisName.setObjectName("LA_yAxisName")
        self.gridLayout_5.addWidget(self.LA_yAxisName, 1, 2, 1, 1)
        self.ChB_noAxisName = QtWidgets.QCheckBox(self.GB_axisFormat)
        self.ChB_noAxisName.setObjectName("ChB_noAxisName")
        self.gridLayout_5.addWidget(self.ChB_noAxisName, 0, 1, 1, 1)
        self.LE_yAxisName = QtWidgets.QLineEdit(self.GB_axisFormat)
        self.LE_yAxisName.setObjectName("LE_yAxisName")
        self.gridLayout_5.addWidget(self.LE_yAxisName, 2, 2, 1, 1)
        self.LE_xAxisName = QtWidgets.QLineEdit(self.GB_axisFormat)
        self.LE_xAxisName.setObjectName("LE_xAxisName")
        self.gridLayout_5.addWidget(self.LE_xAxisName, 2, 1, 1, 1)
        self.LA_secondaryTicksInterval = QtWidgets.QLabel(self.GB_axisFormat)
        self.LA_secondaryTicksInterval.setObjectName("LA_secondaryTicksInterval")
        self.gridLayout_5.addWidget(self.LA_secondaryTicksInterval, 4, 2, 1, 1)
        self.LA_yAxisFormat = QtWidgets.QLabel(self.GB_axisFormat)
        self.LA_yAxisFormat.setObjectName("LA_yAxisFormat")
        self.gridLayout_5.addWidget(self.LA_yAxisFormat, 6, 0, 1, 1)
        self.ChB_autoTicks = QtWidgets.QCheckBox(self.GB_axisFormat)
        self.ChB_autoTicks.setChecked(True)
        self.ChB_autoTicks.setObjectName("ChB_autoTicks")
        self.gridLayout_5.addWidget(self.ChB_autoTicks, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.GB_axisFormat, 2, 0, 1, 2)
        self.tabWidget.addTab(self.Options, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.GB_numberFormat.setTitle(_translate("Form", "Number format"))
        self.LA_xNumberFormat.setText(_translate("Form", "X:"))
        self.LA_yNumberFormat.setText(_translate("Form", "Y:"))
        self.LA_numberOfDigits.setText(_translate("Form", "Number of digits"))
        self.CoB_xNumberFormat.setItemText(0, _translate("Form", "Float"))
        self.CoB_xNumberFormat.setItemText(1, _translate("Form", "Integer"))
        self.CoB_xNumberFormat.setItemText(2, _translate("Form", "Scientific"))
        self.CoB_yNumberFormat.setItemText(0, _translate("Form", "Float"))
        self.CoB_yNumberFormat.setItemText(1, _translate("Form", "Integer"))
        self.CoB_yNumberFormat.setItemText(2, _translate("Form", "Scientific"))
        self.LA_typeNumberFormat.setText(_translate("Form", "Type"))
        self.GB_grid.setTitle(_translate("Form", "Grid"))
        self.ChB_enableXGrid.setText(_translate("Form", "Enable X-grid"))
        self.ChB_enableYGrid.setText(_translate("Form", "Enable Y-grid"))
        self.LA_gridOpacity.setText(_translate("Form", "Grid opcacity"))
        self.GB_axisScaling.setTitle(_translate("Form", "Axis Scaling"))
        self.LA_xMax.setText(_translate("Form", "max"))
        self.LA_xMin.setText(_translate("Form", "min"))
        self.LA_xScaling.setText(_translate("Form", "X:"))
        self.LA_yScaling.setText(_translate("Form", "Y:"))
        self.LA_autoscale.setText(_translate("Form", "Autoscale"))
        self.GB_axisFormat.setTitle(_translate("Form", "Axis format"))
        self.LA_xAxisFormat.setText(_translate("Form", "X:"))
        self.LA_primaryTicksInterval.setText(_translate("Form", "Primary ticks interval"))
        self.LA_xAxisName.setText(_translate("Form", "X-axis name"))
        self.LA_yAxisName.setText(_translate("Form", "Y-axis name"))
        self.ChB_noAxisName.setText(_translate("Form", "No axis name"))
        self.LA_secondaryTicksInterval.setText(_translate("Form", "Secondary ticks interval"))
        self.LA_yAxisFormat.setText(_translate("Form", "Y:"))
        self.ChB_autoTicks.setText(_translate("Form", "Auto ticks"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Options), _translate("Form", "Graph Settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Fitting"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Data selector"))
