# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGrapherViewUi.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_grapherWidget(object):
    def setupUi(self, grapherWidget):
        grapherWidget.setObjectName("grapherWidget")
        grapherWidget.resize(939, 737)
        self.gridLayout = QtWidgets.QGridLayout(grapherWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(grapherWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(9)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_graph = QtWidgets.QWidget()
        self.tab_graph.setObjectName("tab_graph")
        self.tabWidget.addTab(self.tab_graph, "")
        self.tab_data = QtWidgets.QWidget()
        self.tab_data.setObjectName("tab_data")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_data)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.tab_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.tab_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.tableView = QtWidgets.QTableView(self.widget_2)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_2.addWidget(self.tableView)
        self.horizontalLayout.addWidget(self.widget_2)
        self.tabWidget.addTab(self.tab_data, "")
        self.gridLayout.addWidget(self.tabWidget, 2, 0, 1, 1)
        self.DataManagerWidget = QtWidgets.QWidget(grapherWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DataManagerWidget.sizePolicy().hasHeightForWidth())
        self.DataManagerWidget.setSizePolicy(sizePolicy)
        self.DataManagerWidget.setObjectName("DataManagerWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.DataManagerWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dataManagerLayout = QtWidgets.QVBoxLayout()
        self.dataManagerLayout.setObjectName("dataManagerLayout")
        self.la_dataFiles = QtWidgets.QLabel(self.DataManagerWidget)
        self.la_dataFiles.setObjectName("la_dataFiles")
        self.dataManagerLayout.addWidget(self.la_dataFiles)
        self.dataLoaderWidget = QtWidgets.QWidget(self.DataManagerWidget)
        self.dataLoaderWidget.setObjectName("dataLoaderWidget")
        self.dataManagerLayout.addWidget(self.dataLoaderWidget)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.DataManagerWidget)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_2.addTab(self.tab_2, "")
        self.dataManagerLayout.addWidget(self.tabWidget_2)
        self.verticalLayout_3.addLayout(self.dataManagerLayout)
        self.gridLayout.addWidget(self.DataManagerWidget, 2, 1, 1, 1)

        self.retranslateUi(grapherWidget)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(grapherWidget)

    def retranslateUi(self, grapherWidget):
        _translate = QtCore.QCoreApplication.translate
        grapherWidget.setWindowTitle(_translate("grapherWidget", "MainGrapher"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_graph), _translate("grapherWidget", "Graph"))
        self.label.setText(_translate("grapherWidget", "Detected data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_data), _translate("grapherWidget", "Data"))
        self.la_dataFiles.setText(_translate("grapherWidget", "Data Manager"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("grapherWidget", "Tab 1"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("grapherWidget", "Tab 2"))


